"""The base classes: an agent is structure, a session is the history that structure runs on."""

from __future__ import annotations

import contextlib
import subprocess
import sys
import threading
import uuid
import weakref
from abc import ABC, abstractmethod
from typing import IO

from .config import AgentConfig


def _tee(source: IO[str], sink: IO[str], captured: list[str]) -> None:
    """Copies `source` into `sink` line by line, keeping every line in `captured`.

    A sink that has gone away -- a flow piped into something that has exited -- stops the copying
    but not the reading: a pipe nobody drains blocks the agent writing to it, and the turn would
    then be waiting on an agent that is itself waiting.
    """
    for line in source:
        captured.append(line)
        with contextlib.suppress(OSError):
            sink.write(line)
            sink.flush()


class SessionBase(ABC):
    """One conversation with one agent, kept alive across turns.

    The first :meth:`run` opens the backend session; every later one resumes it, so the agent
    still has the earlier turns in context. Discarding the session is how a flow forgets:
    a new instance starts from nothing.
    """

    def __init__(self, agent: AgentBase):
        """Initializes an unopened session and registers it with its agent.

        Args:
          agent: The agent whose config every turn of this session runs at.
        """
        self._agent = agent
        self._id: str | None = None
        self._lock = (
            threading.Lock()
        )  # a conversation is a sequence: one turn at a time
        # A session drops itself from its agent when it is collected, so the agent neither holds
        # a flow's discarded sessions nor has to prune them while someone is reading them.
        agent._sessions.append(weakref.ref(self, agent._sessions.remove))

    @property
    def id(self) -> str:
        """The backend's id for this conversation, which every turn after the first resumes.

        Raises:
          RuntimeError: If no turn has landed yet, so the backend has not named the session.
        """
        if self._id is None:
            raise RuntimeError("session has not run a turn yet")
        return self._id

    def run(self, prompt: str) -> str:
        """Sends one turn, opening the session on the first call and resuming it after.

        Turns of one session are serialized, so a session shared by two threads holds one
        conversation rather than interleaving two. Both of the agent's streams are teed to ours
        as they arrive, so a long turn stays watchable. A failed turn leaves the session
        unopened, so the next call retries the turn the same way rather than resuming a session
        that may not exist. An anchored agent is run through coganchor, which is what puts the
        turn's files and commands on another machine while the conversation stays here.

        Args:
          prompt: The input prompt for this turn.

        Returns:
          The response generated by the agent, stripped.

        Raises:
          subprocess.CalledProcessError: If the agent CLI exits nonzero. Both streams are
            attached to it as diagnostics.
        """
        with self._lock:
            argv, stdin = self._turn(prompt)
            if (anchor := self._agent.config.anchor) is not None:
                # Spawned rather than called: coganchor's supervisor forks the agent and takes
                # the process's signal handling with it, which a flow pumping turns from
                # threads of its own has no way to lend it.
                argv = anchor.command(argv)
            with subprocess.Popen(
                argv,
                # No prompt on stdin means no stdin at all: inheriting ours would let the agent
                # read the terminal a flow is being watched from.
                stdin=subprocess.PIPE if stdin is not None else subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                encoding="utf-8",
                # The agents draw progress bars and check marks: their bytes must never fail a
                # turn, whatever encoding the machine running the flow happens to be set to.
                errors="replace",
            ) as proc:
                assert proc.stdout is not None and proc.stderr is not None
                out: list[str] = []
                err: list[str] = []
                # Every pipe drains from the moment the agent starts: it puts its progress on
                # stderr and only the final message on stdout, and a prompt larger than the pipe
                # buffer would deadlock against an agent that prints before reading all of it.
                pumps = [
                    threading.Thread(target=_tee, args=(proc.stdout, sys.stdout, out)),
                    threading.Thread(target=_tee, args=(proc.stderr, sys.stderr, err)),
                ]
                for pump in pumps:
                    pump.start()
                if stdin is not None:
                    assert proc.stdin is not None
                    # An agent that exits before reading the prompt is a failed turn, reported
                    # by its exit status rather than as a broken pipe here.
                    with contextlib.suppress(BrokenPipeError):
                        try:
                            proc.stdin.write(stdin)
                        finally:
                            proc.stdin.close()
                for pump in pumps:
                    pump.join()
                status = proc.wait()

            stdout = "".join(out)
            if status != 0:
                raise subprocess.CalledProcessError(status, argv, stdout, "".join(err))
            if self._id is None:  # an id is fixed for the life of the session it names
                # Separated, so that a stdout without a trailing newline cannot glue the first
                # line of stderr onto the last of stdout and hide a line the id is read from.
                self._id = self._read_session_id(stdout + "\n" + "".join(err))
                # The backend logs this session from here on but never says whose it is, so the
                # moment its id becomes known is the moment the agent takes note of it.
                self._agent._opened.append(self._id)
            return stdout.strip()

    @abstractmethod
    def _turn(self, prompt: str) -> tuple[list[str], str | None]:
        """Builds the CLI call for one turn.

        Args:
          prompt: The input prompt for this turn.

        Returns:
          The command to run and the text to write to its stdin, or None when the prompt is
          already inside the command. The command opens a new session while the session is
          unopened, and resumes that session once it has an id.
        """

    @abstractmethod
    def _read_session_id(self, transcript: str) -> str:
        """Reads back the id the backend gave this session, once the opening turn has landed.

        Args:
          transcript: Everything the turn printed, on stdout and stderr alike.

        Returns:
          The backend's session id, which every later turn resumes.
        """


class AgentBase(ABC):
    """A coding agent behind a uniform interface: structure only, and no history.

    An agent says which model to run at which effort, and is one agent apart from that: a flow
    that reviews its own work runs two of them at one configuration, and they are not the same
    agent. The conversation lives in the :class:`SessionBase` it launches, so a flow decides for
    itself whether turns share context -- a fresh session per turn is a Ralph loop, one session
    across turns is a stateful one.
    """

    def __init__(self, config: AgentConfig, *, name: str | None = None):
        """Initializes an agent that has launched nothing yet.

        Args:
          config: The model and effort every session of this agent runs at.
          name: What to call this agent, defaulting to one nothing else answers to. Two agents
            sharing a name are one agent to a trace, which is how the roles of a flow survive
            being restarted; two left unnamed are two, which is how one configuration driven
            twice -- an actor and the reviewer reading its work -- stays two.
        """
        self._config = config
        self._id = name or f"{type(self).__name__}#{uuid.uuid4().hex[:8]}"
        self._sessions: list[weakref.ref[SessionBase]] = []
        self._opened: list[str] = []

    @property
    def id(self) -> str:
        """What this agent is called, and what a trace groups its sessions under."""
        return self._id

    @property
    def opened(self) -> list[str]:
        """The backend's id for every session this agent has opened, oldest first.

        What :attr:`sessions` cannot say: a flow that drops a session per turn keeps none of
        them, but the backend logged them all, and a trace of the run has to know whose they
        were. Ids rather than sessions, so remembering a day of turns costs a list of strings.
        """
        return list(self._opened)

    @property
    def config(self) -> AgentConfig:
        """The model and effort every session of this agent runs at."""
        return self._config

    @property
    def sessions(self) -> list[SessionBase]:
        """The sessions launched on this agent and still held by someone, oldest first.

        Held weakly, so a flow that launches a session per turn -- a Ralph loop runs for days --
        does not grow an agent by one session a turn for as long as it runs.
        """
        return [session for ref in self._sessions if (session := ref()) is not None]

    @abstractmethod
    def launch(self) -> SessionBase:
        """Creates a new session, which stays unopened until its first turn.

        Returns:
          A session with no history yet.
        """
