"""The base classes: an agent is structure, a session is the history that structure runs on."""

from __future__ import annotations

import subprocess
import sys
import threading
from abc import ABC, abstractmethod
from typing import IO


def _tee(source: IO[str], sink: IO[str], captured: list[str]) -> None:
    """Copies `source` into `sink` line by line, keeping every line in `captured`."""
    for line in source:
        sink.write(line)
        sink.flush()
        captured.append(line)


class SessionBase(ABC):
    """One conversation with one agent, kept alive across turns.

    The first :meth:`run` opens the backend session; every later one resumes it, so the agent
    still has the earlier turns in context. Discarding the session is how a flow forgets:
    a new instance starts from nothing.

    Attributes:
      agent: The agent whose model and effort every turn of this session uses.
      session_id: The backend's id for this conversation, or None until the first turn lands.
    """

    def __init__(self, agent: AgentBase):
        """Initializes an unopened session on the given agent.

        Args:
          agent: The agent whose model and effort every turn of this session uses.
        """
        self.agent = agent
        self.session_id: str | None = None

    def run(self, prompt: str) -> str:
        """Sends one turn, opening the session on the first call and resuming it after.

        Both of the agent's streams are teed to ours as they arrive, so a long turn stays
        watchable. A failed turn leaves `session_id` untouched, so the next call retries the
        turn the same way rather than resuming a session that may not exist.

        Args:
          prompt: The input prompt for this turn.

        Returns:
          The response generated by the agent, stripped.

        Raises:
          subprocess.CalledProcessError: If the agent CLI exits nonzero. Both streams are
            attached to it as diagnostics.
        """
        argv, stdin = self._turn(prompt)
        with subprocess.Popen(
            argv,
            stdin=subprocess.PIPE if stdin is not None else None,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        ) as proc:
            if stdin is not None:
                assert proc.stdin is not None
                proc.stdin.write(stdin)  # the agent CLIs read the whole prompt before replying
                proc.stdin.close()

            assert proc.stdout is not None and proc.stderr is not None
            out: list[str] = []
            err: list[str] = []
            # Both pipes have to drain at once: the agents put their progress on stderr and only
            # the final message on stdout, so draining one would fill and block the other.
            pump = threading.Thread(target=_tee, args=(proc.stderr, sys.stderr, err))
            pump.start()
            _tee(proc.stdout, sys.stdout, out)
            pump.join()
            status = proc.wait()

        stdout = "".join(out)
        if status != 0:
            raise subprocess.CalledProcessError(status, argv, stdout, "".join(err))
        if self.session_id is None:  # an id is fixed for the life of the session it names
            self.session_id = self._read_session_id(stdout + "".join(err))
        return stdout.strip()

    @abstractmethod
    def _turn(self, prompt: str) -> tuple[list[str], str | None]:
        """Builds the CLI call for one turn.

        Args:
          prompt: The input prompt for this turn.

        Returns:
          The command to run and the text to write to its stdin, or None when the prompt is
          already inside the command. The command opens a new session while `session_id` is
          None, and resumes that session once it is set.
        """

    @abstractmethod
    def _read_session_id(self, transcript: str) -> str:
        """Reads back the id the backend gave this session, once the opening turn has landed.

        Args:
          transcript: Everything the turn printed, on stdout and stderr alike.

        Returns:
          The backend's session id, which every later turn resumes.
        """


class AgentBase(ABC):
    """A coding agent behind a uniform interface: structure only, and no history.

    An agent says which model to run at which effort. The conversation lives in the
    :class:`SessionBase` it opens, so a flow decides for itself whether turns share context --
    a fresh session per turn is a Ralph loop, one session across turns is a stateful one.

    Attributes:
      model: The model name or identifier for the agent.
      effort: The effort level for the agent's responses.
    """

    def __init__(self, *, model: str, effort: str):
        """Initializes the agent with the given model and effort level.

        Args:
          model: The model name or identifier for the agent.
          effort: The effort level for the agent's responses.
        """
        self.model = model
        self.effort = effort

    @abstractmethod
    def start(self) -> SessionBase:
        """Creates a new session, which stays unopened until its first turn.

        Returns:
          A session with no history yet.
        """

    def run(self, prompt: str) -> str:
        """Runs one turn in a throwaway session, so nothing carries over to the next call.

        The session, and the backend session it opened, are dropped on return.

        Args:
          prompt: The input prompt to the agent.

        Returns:
          The response generated by the agent.
        """
        return self.start().run(prompt)
