"""The agent base class and the CLI plumbing every concrete agent shares."""

from __future__ import annotations

import subprocess
import sys
from abc import ABC, abstractmethod


class AgentBase(ABC):
    """A coding agent behind a uniform interface.

    Callers only ever touch :meth:`run`, so the concrete backend stays hidden.

    Attributes:
      model: The model name or identifier for the agent.
      effort: The effort level for the agent's responses.
    """

    def __init__(self, *, model: str, effort: str):
        """Initializes the agent with the given model and effort level.

        Args:
          model: The model name or identifier for the agent.
          effort: The effort level for the agent's responses.
        """
        self.model = model
        self.effort = effort

    @abstractmethod
    def run(self, prompt: str) -> str:
        """Runs the agent with the given prompt and returns the response.

        Args:
          prompt: The input prompt to the agent.

        Returns:
          The response generated by the agent.
        """

    def _run_cli(self, argv: list[str], stdin: str | None) -> str:
        """Runs an agent CLI, teeing its stdout to ours while capturing it.

        Args:
          argv: The command to run.
          stdin: The text to write to the command's stdin, or None when the prompt is already
            inside argv.

        Returns:
          The captured stdout, stripped.

        Raises:
          subprocess.CalledProcessError: If the command exits nonzero.
        """
        proc = subprocess.Popen(
            argv,
            stdin=subprocess.PIPE if stdin is not None else None,
            stdout=subprocess.PIPE,
            text=True,
        )
        if stdin is not None:
            assert proc.stdin is not None
            proc.stdin.write(stdin)  # the agent CLIs consume the whole prompt before replying
            proc.stdin.close()

        assert proc.stdout is not None
        captured: list[str] = []
        for line in proc.stdout:
            sys.stdout.write(line)  # tee: pass the agent's output straight through
            sys.stdout.flush()
            captured.append(line)

        if proc.wait() != 0:
            raise subprocess.CalledProcessError(proc.returncode, argv)
        return "".join(captured).strip()
